/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryTestRouteImport } from './routes/sentry-test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResumesRouteImport } from './routes/_app.resumes'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInterviewPrepRouteImport } from './routes/_app.interview-prep'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppAtsHistoryRouteImport } from './routes/_app.ats-history'
import { Route as AppAtsRouteImport } from './routes/_app.ats'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppResumesIndexRouteImport } from './routes/_app.resumes.index'
import { Route as AppResumesTemplatesRouteImport } from './routes/_app.resumes.templates'
import { Route as AppResumesSetupRouteImport } from './routes/_app.resumes.setup'
import { Route as AppResumesIdRouteImport } from './routes/_app.resumes.$id'
import { Route as AppOptimizerResumeIdRouteImport } from './routes/_app.optimizer.$resumeId'
import { Route as AppInterviewPrepSessionIdRouteImport } from './routes/_app.interview-prep.$sessionId'

const SentryTestRoute = SentryTestRouteImport.update({
  id: '/sentry-test',
  path: '/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewPrepRoute = AppInterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsHistoryRoute = AppAtsHistoryRouteImport.update({
  id: '/ats-history',
  path: '/ats-history',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsRoute = AppAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesTemplatesRoute = AppResumesTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesSetupRoute = AppResumesSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesIdRoute = AppResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppOptimizerResumeIdRoute = AppOptimizerResumeIdRouteImport.update({
  id: '/optimizer/$resumeId',
  path: '/optimizer/$resumeId',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewPrepSessionIdRoute =
  AppInterviewPrepSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AppInterviewPrepRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/applications': typeof AppApplicationsRoute
  '/ats': typeof AppAtsRoute
  '/ats-history': typeof AppAtsHistoryRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview-prep': typeof AppInterviewPrepRouteWithChildren
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/resumes': typeof AppResumesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/interview-prep/$sessionId': typeof AppInterviewPrepSessionIdRoute
  '/optimizer/$resumeId': typeof AppOptimizerResumeIdRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/resumes/setup': typeof AppResumesSetupRoute
  '/resumes/templates': typeof AppResumesTemplatesRoute
  '/resumes/': typeof AppResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/applications': typeof AppApplicationsRoute
  '/ats': typeof AppAtsRoute
  '/ats-history': typeof AppAtsHistoryRoute
  '/copilot': typeof AppCopilotRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview-prep': typeof AppInterviewPrepRouteWithChildren
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/interview-prep/$sessionId': typeof AppInterviewPrepSessionIdRoute
  '/optimizer/$resumeId': typeof AppOptimizerResumeIdRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/resumes/setup': typeof AppResumesSetupRoute
  '/resumes/templates': typeof AppResumesTemplatesRoute
  '/resumes': typeof AppResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentry-test': typeof SentryTestRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/ats': typeof AppAtsRoute
  '/_app/ats-history': typeof AppAtsHistoryRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/interview-prep': typeof AppInterviewPrepRouteWithChildren
  '/_app/jobs': typeof AppJobsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/resumes': typeof AppResumesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/interview-prep/$sessionId': typeof AppInterviewPrepSessionIdRoute
  '/_app/optimizer/$resumeId': typeof AppOptimizerResumeIdRoute
  '/_app/resumes/$id': typeof AppResumesIdRoute
  '/_app/resumes/setup': typeof AppResumesSetupRoute
  '/_app/resumes/templates': typeof AppResumesTemplatesRoute
  '/_app/resumes/': typeof AppResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sentry-test'
    | '/applications'
    | '/ats'
    | '/ats-history'
    | '/copilot'
    | '/dashboard'
    | '/interview-prep'
    | '/jobs'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/resumes'
    | '/settings'
    | '/login'
    | '/signup'
    | '/interview-prep/$sessionId'
    | '/optimizer/$resumeId'
    | '/resumes/$id'
    | '/resumes/setup'
    | '/resumes/templates'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sentry-test'
    | '/applications'
    | '/ats'
    | '/ats-history'
    | '/copilot'
    | '/dashboard'
    | '/interview-prep'
    | '/jobs'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/login'
    | '/signup'
    | '/interview-prep/$sessionId'
    | '/optimizer/$resumeId'
    | '/resumes/$id'
    | '/resumes/setup'
    | '/resumes/templates'
    | '/resumes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sentry-test'
    | '/_app/applications'
    | '/_app/ats'
    | '/_app/ats-history'
    | '/_app/copilot'
    | '/_app/dashboard'
    | '/_app/interview-prep'
    | '/_app/jobs'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_app/recommendations'
    | '/_app/resumes'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/interview-prep/$sessionId'
    | '/_app/optimizer/$resumeId'
    | '/_app/resumes/$id'
    | '/_app/resumes/setup'
    | '/_app/resumes/templates'
    | '/_app/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SentryTestRoute: typeof SentryTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-test': {
      id: '/sentry-test'
      path: '/sentry-test'
      fullPath: '/sentry-test'
      preLoaderRoute: typeof SentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes': {
      id: '/_app/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-prep': {
      id: '/_app/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof AppInterviewPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats-history': {
      id: '/_app/ats-history'
      path: '/ats-history'
      fullPath: '/ats-history'
      preLoaderRoute: typeof AppAtsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats': {
      id: '/_app/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AppAtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/': {
      id: '/_app/resumes/'
      path: '/'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/templates': {
      id: '/_app/resumes/templates'
      path: '/templates'
      fullPath: '/resumes/templates'
      preLoaderRoute: typeof AppResumesTemplatesRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/setup': {
      id: '/_app/resumes/setup'
      path: '/setup'
      fullPath: '/resumes/setup'
      preLoaderRoute: typeof AppResumesSetupRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/resumes/$id': {
      id: '/_app/resumes/$id'
      path: '/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AppResumesIdRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/optimizer/$resumeId': {
      id: '/_app/optimizer/$resumeId'
      path: '/optimizer/$resumeId'
      fullPath: '/optimizer/$resumeId'
      preLoaderRoute: typeof AppOptimizerResumeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-prep/$sessionId': {
      id: '/_app/interview-prep/$sessionId'
      path: '/$sessionId'
      fullPath: '/interview-prep/$sessionId'
      preLoaderRoute: typeof AppInterviewPrepSessionIdRouteImport
      parentRoute: typeof AppInterviewPrepRoute
    }
  }
}

interface AppInterviewPrepRouteChildren {
  AppInterviewPrepSessionIdRoute: typeof AppInterviewPrepSessionIdRoute
}

const AppInterviewPrepRouteChildren: AppInterviewPrepRouteChildren = {
  AppInterviewPrepSessionIdRoute: AppInterviewPrepSessionIdRoute,
}

const AppInterviewPrepRouteWithChildren =
  AppInterviewPrepRoute._addFileChildren(AppInterviewPrepRouteChildren)

interface AppResumesRouteChildren {
  AppResumesIdRoute: typeof AppResumesIdRoute
  AppResumesSetupRoute: typeof AppResumesSetupRoute
  AppResumesTemplatesRoute: typeof AppResumesTemplatesRoute
  AppResumesIndexRoute: typeof AppResumesIndexRoute
}

const AppResumesRouteChildren: AppResumesRouteChildren = {
  AppResumesIdRoute: AppResumesIdRoute,
  AppResumesSetupRoute: AppResumesSetupRoute,
  AppResumesTemplatesRoute: AppResumesTemplatesRoute,
  AppResumesIndexRoute: AppResumesIndexRoute,
}

const AppResumesRouteWithChildren = AppResumesRoute._addFileChildren(
  AppResumesRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAtsRoute: typeof AppAtsRoute
  AppAtsHistoryRoute: typeof AppAtsHistoryRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewPrepRoute: typeof AppInterviewPrepRouteWithChildren
  AppJobsRoute: typeof AppJobsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppResumesRoute: typeof AppResumesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppOptimizerResumeIdRoute: typeof AppOptimizerResumeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppAtsRoute: AppAtsRoute,
  AppAtsHistoryRoute: AppAtsHistoryRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewPrepRoute: AppInterviewPrepRouteWithChildren,
  AppJobsRoute: AppJobsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppResumesRoute: AppResumesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppOptimizerResumeIdRoute: AppOptimizerResumeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SentryTestRoute: SentryTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
